dist: trusty

language: go

go:
  - "1.9.x"
  - "1.10.x"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7

before_install:
  # Install goveralls for code coverage
  - go get github.com/mattn/goveralls

  # Install Bazel.
  - wget https://github.com/bazelbuild/bazel/releases/download/0.11.0/bazel_0.11.0-linux-x86_64.deb
  - sudo dpkg -i bazel_0.11.0-linux-x86_64.deb

  # Compile and install Redis.
  - wget https://github.com/antirez/redis/archive/4.0.8.tar.gz
  - tar zxf 4.0.8.tar.gz
  - cd redis-4.0.8
  - make -j4
  - sudo make install
  - cd ..

  # Compile the SessionGate module.
  - git clone https://github.com/f0rmiga/sessiongate
  - cd sessiongate
  - bazel build //...
  - cd ..

  # Run Redis with SessionGate loaded.
  - redis-server --daemonize yes --loadmodule $(pwd)/sessiongate/bazel-bin/sessiongate.so

after_success:
  - $GOPATH/bin/goveralls -service=travis-ci

env:
  global:
    - CC=gcc-7
    - CXX=g++-7
